sim:
  dt: 0.002
  asset_path: "mujoco/SundayA1_short_new/scene.xml"
  urdf_path: "urdf/SundayA1_short_new/robot.urdf"
real:
  imu_port:
    port: "/dev/ttyACM2"
    baudrate: 9600
  n_motors: 12
  motor_controllers:
    - name: "arm"
      motor_ids: [1, 2, 3, 4, 5, 30, 11, 12, 13, 14, 15, 31]
      sim_idxs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
      sign_change: [-1, 1, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1]
      serial_config:
        port: "/dev/ttyACM2"
        baudrate: 1000000
  calibration_file: "configs/zero_position.csv"
control:
  kp_torque: 20
  kd_torque: 1
policy:
  model_path: "models/policy_leo.pt"
default_qpos: [
  0, 0, 0, 0, 0, 0,
  0, 0., 0, 0, 0, 0,
]